import type { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import { Nav } from "./components/Nav";
import { Footer } from "./components/Footer";

const CormorantGaramond = Cormorant_Garamond({ 
  weight: "600",
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Laura Potter | M.C., L.C.P.C. Crossed Hearts Counseling",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={CormorantGaramond.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
